module SeederKit
  class SeedFileGenerator
    def call(seed_plan)
      tables = seed_plan.fetch(:tables)
      variable_names_by_table = tables.to_h { |table| [ table.fetch(:name), table.fetch(:variable_name) ] }
      sections = []

      sections << %(require "securerandom") if uses_secure_random?(tables)
      sections << "# Generated by SeederKit"

      tables.each do |table|
        sections << create_statement_for(table, variable_names_by_table)
      end

      sections.join("\n\n")
    end

    private

    def create_statement_for(table, variable_names_by_table)
      assignments = assignments_for(table, variable_names_by_table)

      if assignments.empty?
        "#{table.fetch(:variable_name)} = #{table.fetch(:model_name)}.create!"
      else
        <<~RUBY.strip
          #{table.fetch(:variable_name)} = #{table.fetch(:model_name)}.create!(
          #{assignments.join(",\n")}
          )
        RUBY
      end
    end

    def assignments_for(table, variable_names_by_table)
      table.fetch(:columns).filter_map do |column|
        next if column[:default_provided]

        value = value_for(column, variable_names_by_table)
        next unless value

        "  #{column.fetch(:name)}: #{value}"
      end
    end

    def value_for(column, variable_names_by_table)
      if column[:foreign_table]
        parent_variable_name = variable_names_by_table[column.fetch(:foreign_table)]
        return "#{parent_variable_name}.id" if parent_variable_name
      end

      generated_value_for(column)
    end

    def generated_value_for(column)
      column_name = column.fetch(:name)

      return %("user@example.com") if column_name.match?(/email/i)
      return %("password") if column_name.match?(/password/i)

      case column.fetch(:type)
      when :string
        "Example #{column_name.titleize}".inspect
      when :text
        %("Example long text")
      when :integer, :bigint
        "1"
      when :float
        "1.0"
      when :decimal
        "9.99"
      when :boolean
        "true"
      when :date
        "Date.today"
      when :datetime
        "Time.current"
      when :json, :jsonb
        "{}"
      when :uuid
        "SecureRandom.uuid"
      end
    end

    def uses_secure_random?(tables)
      tables.any? do |table|
        table.fetch(:columns).any? { |column| column.fetch(:type) == :uuid && !column[:default] }
      end
    end
  end
end
