export type ColumnType =
  | "string"
  | "text"
  | "integer"
  | "bigint"
  | "float"
  | "decimal"
  | "boolean"
  | "date"
  | "datetime"
  | "json"
  | "jsonb"
  | "uuid";

export type Column = {
  name: string;
  type: ColumnType;
  null: boolean;
  default: string | number | boolean | null;
  defaultProvided: boolean;
  foreignTable?: string;
};

export type Table = {
  name: string;
  modelName: string;
  columns: Column[];
};

export type SeedPlanTable = Table & {
  variableName: string;
};

export type ParsedSchema = {
  tables: Table[];
};

export type SeedPlan = {
  tables: SeedPlanTable[];
};

export class SchemaParseError extends Error {}
export class DependencyCycleError extends Error {}

const supportedColumnTypes = new Set<ColumnType>([
  "string",
  "text",
  "integer",
  "bigint",
  "float",
  "decimal",
  "boolean",
  "date",
  "datetime",
  "json",
  "jsonb",
  "uuid",
]);

const ignoredColumnNames = new Set(["id", "created_at", "updated_at"]);

const internalTablePatterns = [
  /^schema_migrations$/,
  /^ar_internal_metadata$/,
  /^active_storage_/,
  /^action_text_/,
  /^action_mailbox_/,
  /^seeder_kit_/,
];

export function generateSeeds(schemaText: string): string {
  return generateSeedFile(buildSeedPlan(parseSchema(schemaText)));
}

export function parseSchema(schemaText: string): ParsedSchema {
  if (schemaText.trim() === "") {
    throw new SchemaParseError("Paste a Rails schema.rb file to generate seeds.");
  }

  const tablesByName = new Map<string, Table>();
  const foreignKeys: Array<{ fromTable: string; toTable: string; column?: string }> = [];
  let currentTable: Table | undefined;

  for (const line of schemaText.split(/\r?\n/)) {
    const tableName = createTableName(line);

    if (tableName) {
      currentTable = buildTable(tableName);

      if (currentTable) {
        tablesByName.set(tableName, currentTable);
      }

      continue;
    }

    if (currentTable && endBlock(line)) {
      currentTable = undefined;
      continue;
    }

    if (currentTable) {
      const column = parseColumn(line);

      if (column && !ignoredColumnNames.has(column.name)) {
        currentTable.columns.push(column);
      }

      if (column) {
        continue;
      }
    }

    const foreignKey = parseForeignKey(line);

    if (foreignKey) {
      foreignKeys.push(foreignKey);
    }
  }

  if (tablesByName.size === 0) {
    throw new SchemaParseError("No supported application tables were found in the pasted schema.");
  }

  applyExplicitForeignKeys(tablesByName, foreignKeys);
  inferObviousForeignKeys(tablesByName);

  return {
    tables: Array.from(tablesByName.values()).sort((left, right) => left.name.localeCompare(right.name)),
  };
}

export function buildSeedPlan(parsedSchema: ParsedSchema): SeedPlan {
  const tablesByName = new Map(parsedSchema.tables.map((table) => [table.name, cloneTable(table)]));
  const orderedNames = dependencyOrder(tablesByName);

  return {
    tables: orderedNames.map((tableName) => {
      const table = tablesByName.get(tableName);

      if (!table) {
        throw new Error(`Missing table ${tableName}`);
      }

      return {
        ...table,
        variableName: variableNameFor(table.name),
      };
    }),
  };
}

export function generateSeedFile(seedPlan: SeedPlan): string {
  const tables = seedPlan.tables;
  const variableNamesByTable = new Map(tables.map((table) => [table.name, table.variableName]));
  const sections: string[] = [];

  if (usesSecureRandom(tables)) {
    sections.push('require "securerandom"');
  }

  sections.push("# Generated by SeederKit");

  for (const table of tables) {
    sections.push(createStatementFor(table, variableNamesByTable));
  }

  return sections.join("\n\n");
}

function buildTable(tableName: string): Table | undefined {
  if (ignoredTable(tableName)) {
    return undefined;
  }

  return {
    name: tableName,
    modelName: classify(tableName),
    columns: [],
  };
}

function createTableName(line: string): string | undefined {
  return line.match(/^\s*create_table\s+["']([^"']+)["']/)?.[1];
}

function endBlock(line: string): boolean {
  return /^\s*end\s*$/.test(line);
}

function parseColumn(line: string): Column | undefined {
  const match = line.match(/^\s*t\.(\w+)\s+["']([^"']+)["'](.*)$/);

  if (!match) {
    return undefined;
  }

  const columnType = match[1] as ColumnType;

  if (!supportedColumnTypes.has(columnType)) {
    return undefined;
  }

  const options = match[3] ?? "";

  return {
    name: match[2],
    type: columnType,
    null: parseNullOption(options),
    default: parseDefaultOption(options),
    defaultProvided: defaultOption(options),
  };
}

function parseForeignKey(line: string): { fromTable: string; toTable: string; column?: string } | undefined {
  const match = line.match(/^\s*add_foreign_key\s+["']([^"']+)["']\s*,\s*["']([^"']+)["'](.*)$/);

  if (!match) {
    return undefined;
  }

  return {
    fromTable: match[1],
    toTable: match[2],
    column: parseStringOption(match[3] ?? "", "column"),
  };
}

function parseNullOption(options: string): boolean {
  const match = options.match(/(?:^|,\s*)null:\s*(true|false)/);
  return match ? match[1] === "true" : true;
}

function parseDefaultOption(options: string): string | number | boolean | null {
  const match = options.match(/(?:^|,\s*)default:\s*("[^"]*"|'[^']*'|[^,\s]+)/);

  if (!match) {
    return null;
  }

  const rawValue = match[1];

  if (rawValue === "true") return true;
  if (rawValue === "false") return false;
  if (rawValue === "nil") return null;
  if (/^["'].*["']$/.test(rawValue)) return rawValue.slice(1, -1);
  if (/^-?\d+$/.test(rawValue)) return Number.parseInt(rawValue, 10);
  if (/^-?\d+\.\d+$/.test(rawValue)) return Number.parseFloat(rawValue);

  return rawValue;
}

function defaultOption(options: string): boolean {
  return /(?:^|,\s*)default:/.test(options);
}

function parseStringOption(options: string, optionName: string): string | undefined {
  const match = options.match(new RegExp(`(?:^|,\\s*)${escapeRegExp(optionName)}:\\s*["']([^"']+)["']`));
  return match?.[1];
}

function applyExplicitForeignKeys(
  tablesByName: Map<string, Table>,
  foreignKeys: Array<{ fromTable: string; toTable: string; column?: string }>,
): void {
  for (const foreignKey of foreignKeys) {
    const childTable = tablesByName.get(foreignKey.fromTable);
    const parentTable = tablesByName.get(foreignKey.toTable);

    if (!childTable || !parentTable) {
      continue;
    }

    const columnName = foreignKey.column ?? `${singularize(parentTable.name)}_id`;
    markForeignKey(childTable, columnName, parentTable.name);
  }
}

function inferObviousForeignKeys(tablesByName: Map<string, Table>): void {
  for (const table of tablesByName.values()) {
    for (const column of table.columns) {
      if (!column.name.endsWith("_id") || column.foreignTable) {
        continue;
      }

      const candidateTable = pluralize(column.name.slice(0, -3));

      if (tablesByName.has(candidateTable)) {
        markForeignKey(table, column.name, candidateTable);
      }
    }
  }
}

function markForeignKey(table: Table, columnName: string, foreignTable: string): void {
  const column = table.columns.find((candidate) => candidate.name === columnName);

  if (column) {
    column.foreignTable = foreignTable;
  }
}

function dependencyOrder(tablesByName: Map<string, Table>): string[] {
  const permanentMarks = new Set<string>();
  const temporaryMarks = new Set<string>();
  const orderedNames: string[] = [];

  for (const tableName of Array.from(tablesByName.keys()).sort()) {
    visitTable(tableName, tablesByName, permanentMarks, temporaryMarks, orderedNames, []);
  }

  return orderedNames;
}

function visitTable(
  tableName: string,
  tablesByName: Map<string, Table>,
  permanentMarks: Set<string>,
  temporaryMarks: Set<string>,
  orderedNames: string[],
  stack: string[],
): void {
  if (permanentMarks.has(tableName)) {
    return;
  }

  if (temporaryMarks.has(tableName)) {
    const cycle = [...stack, tableName];
    throw new DependencyCycleError(
      `Cannot generate seeds because these tables depend on each other: ${cycle
        .slice(cycle.indexOf(tableName))
        .join(" -> ")}`,
    );
  }

  const table = tablesByName.get(tableName);

  if (!table) {
    return;
  }

  temporaryMarks.add(tableName);

  for (const dependencyName of dependenciesFor(table).sort()) {
    visitTable(dependencyName, tablesByName, permanentMarks, temporaryMarks, orderedNames, [...stack, tableName]);
  }

  temporaryMarks.delete(tableName);
  permanentMarks.add(tableName);
  orderedNames.push(tableName);
}

function dependenciesFor(table: Table): string[] {
  return Array.from(new Set(table.columns.map((column) => column.foreignTable).filter(Boolean) as string[]));
}

function createStatementFor(table: SeedPlanTable, variableNamesByTable: Map<string, string>): string {
  const assignments = assignmentsFor(table, variableNamesByTable);

  if (assignments.length === 0) {
    return `${table.variableName} = ${table.modelName}.create!`;
  }

  return `${table.variableName} = ${table.modelName}.create!(\n${assignments.join(",\n")}\n)`;
}

function assignmentsFor(table: SeedPlanTable, variableNamesByTable: Map<string, string>): string[] {
  return table.columns.flatMap((column) => {
    if (column.defaultProvided) {
      return [];
    }

    const value = valueFor(column, variableNamesByTable);
    return value ? [`  ${column.name}: ${value}`] : [];
  });
}

function valueFor(column: Column, variableNamesByTable: Map<string, string>): string | undefined {
  if (column.foreignTable) {
    const parentVariableName = variableNamesByTable.get(column.foreignTable);

    if (parentVariableName) {
      return `${parentVariableName}.id`;
    }
  }

  return generatedValueFor(column);
}

function generatedValueFor(column: Column): string | undefined {
  if (/email/i.test(column.name)) return '"user@example.com"';
  if (/password/i.test(column.name)) return '"password"';

  switch (column.type) {
    case "string":
      return JSON.stringify(`Example ${titleize(column.name)}`);
    case "text":
      return '"Example long text"';
    case "integer":
    case "bigint":
      return "1";
    case "float":
      return "1.0";
    case "decimal":
      return "9.99";
    case "boolean":
      return "true";
    case "date":
      return "Date.today";
    case "datetime":
      return "Time.current";
    case "json":
    case "jsonb":
      return "{}";
    case "uuid":
      return "SecureRandom.uuid";
  }
}

function usesSecureRandom(tables: SeedPlanTable[]): boolean {
  return tables.some((table) =>
    table.columns.some((column) => column.type === "uuid" && !column.defaultProvided),
  );
}

function ignoredTable(tableName: string): boolean {
  return internalTablePatterns.some((pattern) => pattern.test(tableName));
}

function cloneTable(table: Table): Table {
  return {
    ...table,
    columns: table.columns.map((column) => ({ ...column })),
  };
}

function variableNameFor(tableName: string): string {
  return underscore(singularize(tableName));
}

function classify(tableName: string): string {
  return singularize(tableName)
    .split("_")
    .map((part) => capitalize(part))
    .join("");
}

function titleize(value: string): string {
  return value
    .split("_")
    .map((part) => capitalize(part))
    .join(" ");
}

function underscore(value: string): string {
  return value.replace(/([a-z\d])([A-Z])/g, "$1_$2").toLowerCase();
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function singularize(value: string): string {
  if (value.endsWith("ies")) return `${value.slice(0, -3)}y`;
  if (value.endsWith("ses")) return value.slice(0, -2);
  if (value.endsWith("s") && !value.endsWith("ss")) return value.slice(0, -1);
  return value;
}

function pluralize(value: string): string {
  if (value.endsWith("y")) return `${value.slice(0, -1)}ies`;
  if (value.endsWith("s")) return `${value}es`;
  return `${value}s`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
