import assert from "node:assert/strict";
import test from "node:test";
import { buildSeedPlan, generateSeedFile, generateSeeds, parseSchema, SchemaParseError } from "./seedGenerator.js";

const schema = `ActiveRecord::Schema[8.0].define do
  create_table "users", force: :cascade do |t|
    t.string "email"
    t.datetime "created_at", null: false
  end

  create_table "posts", force: :cascade do |t|
    t.string "title"
    t.integer "user_id", null: false
    t.integer "status", default: 0, null: false
  end

  create_table "seeder_kit_scenarios", force: :cascade do |t|
    t.string "name"
  end

  add_foreign_key "posts", "users"
end`;

test("parses schema tables and skips internal tables", () => {
  const parsed = parseSchema(schema);

  assert.deepEqual(
    parsed.tables.map((table) => table.name),
    ["posts", "users"],
  );

  const post = parsed.tables.find((table) => table.name === "posts");
  const userId = post?.columns.find((column) => column.name === "user_id");

  assert.equal(post?.modelName, "Post");
  assert.equal(userId?.foreignTable, "users");
});

test("orders parent tables before dependent tables", () => {
  const plan = buildSeedPlan(parseSchema(schema));

  assert.deepEqual(
    plan.tables.map((table) => table.name),
    ["users", "posts"],
  );
});

test("generates create statements with foreign key references", () => {
  const seedFile = generateSeedFile(buildSeedPlan(parseSchema(schema)));

  assert.match(seedFile, /user = User\.create!\(/);
  assert.match(seedFile, /email: "user@example.com"/);
  assert.match(seedFile, /post = Post\.create!\(/);
  assert.match(seedFile, /user_id: user\.id/);
  assert.doesNotMatch(seedFile, /status:/);
});

test("generates complete seeds in one call", () => {
  assert.match(generateSeeds(schema), /# Generated by SeederKit/);
});

test("raises a useful error for blank input", () => {
  assert.throws(() => parseSchema(" "), SchemaParseError);
});
