require "test_helper"

module SeederKit
  class SeedFileGeneratorTest < ActiveSupport::TestCase
    test "generates simple create statements with foreign key references" do
      parsed_schema = SchemaParser.new.call(File.read(Rails.root.join("db/schema.rb")))
      seed_plan = SeedPlanBuilder.new.call(parsed_schema)
      seed_file = SeedFileGenerator.new.call(seed_plan)

      assert_includes seed_file, "# Generated by SeederKit"
      assert_includes seed_file, "user = User.create!("
      assert_includes seed_file, %(email: "user@example.com")
      assert_includes seed_file, "post = Post.create!("
      assert_includes seed_file, "user_id: user.id"
      assert_includes seed_file, "comment = Comment.create!("
      assert_includes seed_file, "post_id: post.id"
      refute_includes seed_file, "status:"
    end

    test "requires securerandom when uuid values are generated" do
      seed_plan = {
        tables: [
          {
            name: "api_tokens",
            model_name: "ApiToken",
            variable_name: "api_token",
            columns: [
              { name: "token", type: :uuid, null: true, default: nil, default_provided: false }
            ]
          }
        ]
      }

      seed_file = SeedFileGenerator.new.call(seed_plan)

      assert_includes seed_file, %(require "securerandom")
      assert_includes seed_file, "token: SecureRandom.uuid"
    end
  end
end
